{% set name = "libvdwxc" %}
{% set version = '0.4.0' %}
{% set build_number = 1 %}

{% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
{% else %}
  {% set mpi_prefix = "nompi" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://launchpad.net/{{ name }}/stable/{{ version }}/+download/{{ name }}-{{ version }}.tar.gz
  sha256: 3524feb5bb2be86b4688f71653502146b181e66f3f75b8bdaf23dd1ae4a56b33

build:
  skip: True  # [not unix]
  number: {{ build_number }}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build_number }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
    - {{ pin_subpackage('libvdwxc', max_pin='x.x') }}
  ignore_run_exports:
    - libgfortran5
 
requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}        # [mpi == 'openmpi' and build_platform != target_platform]
    - make  # [unix]
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - fftw * {{ mpi_prefix }}_*


test:
  requires:
    - python >= 3
  commands:
    - test -f ${PREFIX}/include/vdwxc.h || exit 1   # [unix]
    - test -f ${PREFIX}/include/vdwxcfort.f90 || exit 1  # [unix]
    - test -f ${PREFIX}/include/vdwxc_mpi.h || exit 1  # [unix and (mpi != 'nompi')]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libvdwxc${SHLIB_EXT}']"  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libvdwxcfort${SHLIB_EXT}']"  # [unix]

    
about:
  home: https://libvdwxc.org
  dev_url: https://gitlab.com/libvdwxc/libvdwxc
  doc_url: https://libvdwxc.org/index.html
  license: GPL-3.0-or-later
  license_family: Other
  summary: Portable C library of density functionals with van der Waals interactions for density functional theory


extra:
  recipe-maintainers:
    - gdonval
